export const GET_NEWS = "GET_NEWS"
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS"
export const GET_NEWS_FAIL = "GET_NEWS_FAIL"

export const PENDING_ADD_NEWS = "PENDING_ADD_NEWS"
export const ADD_NEWS = "ADD_NEWS"
export const ADD_NEWS_SUCCESS = "ADD_NEWS_SUCCESS"
export const ADD_NEWS_FAIL = "ADD_NEWS_FAIL"

export const PENDING_UPDATE_NEWS = "PENDING_UPDATE_NEWS"
export const UPDATE_NEWS = "UPDATE_NEWS"
export const UPDATE_NEWS_SUCCESS = "UPDATE_NEWS_SUCCESS"
export const UPDATE_NEWS_FAIL = "UPDATE_NEWS_FAIL"
